#!/bin/sh
source /etc/preinit
script_init
source /etc/preinit.d/b7200_multiboot

echo "current firmware: $(currentFirmware)"
printSoftwareInfo

firmware="$1"

menu="000"
[ -f "/var/lib/hakchi/menu" ] && menu="$(cat /var/lib/hakchi/menu)"
[ "$menu" == "000" ] && menu=""
containsGames "$rootfs$gamepath/$menu/" || menu=""

echo "$firmware" | grep "^$gamepath"

if [ $? -eq 0 ]; then
  firmware="$(echo "$firmware" | sed -e "s#^$gamepath/#$(multiboot_findgamepath)/$menu/#")"
fi

if [ "$firmware" != "_nand_" ]; then
  firmware="$(readlink -f "$firmware")"
  checkFirmware "$firmware" || exit 1
fi

[ "$cfg_firmware" == "$firmware" ] && exit 0
cfg_firmware="$firmware"
save_config

[ "$(currentFirmware)" == "$firmware" ] && exit 0

echo "changing firmware to: $firmware"
rm "/var/lib/hakchi/menu"
reboot
exit 0
